/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Patrick' at '4/1/17 5:25 PM' with Gradle 2.6
 *
 * @author Patrick, @date 4/1/17 5:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
